#!/usr/bin/env node

/*
  Generates vbox.d.ts with type augmentations for alias and design tokens
*/

import * as path from "node:path";
import * as fs from "fs-extra";

const { createJiti } = require("jiti");
const jiti = createJiti(__filename, { debug: true });

const root = process.cwd();
const configs = [
  path.resolve(root, "vbox.config.ts"),
  path.resolve(root, "vbox.config.js"),
];

const loadConfig = async () => {
  for (const config of configs) {
    if (await fs.pathExists(config)) {
      try {
        const mod = jiti(config);
        return mod?.default ?? mod;
      } catch (err) {
        console.error("Failed to load config:", config, err);
      }
    }
  }
  return null;
};

const buildAliasDts = (aliases = {}) => {
  const entries = Object.entries(aliases)
    .map(([k, v]) => `    ${k}: "${v}";`)
    .join("\n");
  return `
interface AliasMap {
${entries || "    // no user aliases"}
}
`;
};

const buildThemeInterface = (values: Record<string, unknown>, type: string) => {
  const entries = Object.entries(values)
    .map(([k]) => `'${k}': true;`)
    .join("\n");

  return `
interface ${type} {
${entries}
}`;
};

const main = async () => {
  const config = await loadConfig();

  if (!config) {
    console.log(
      "Could not find either vbox.config.ts or vbox.config.js file at the root of the project",
    );

    return;
  }

  const aliases = config.alias?.values ?? {};
  const colors = config.theme?.colors ?? {};
  const fontSizes = config.theme?.fontSize ?? {};
  const fontWeights = config.theme?.fontWeight ?? {};
  const fontFamilies = config.theme?.fontFamily ?? {};
  const spacings = config.theme?.spacing ?? {};
  const outFile = path.resolve(root, "vbox.d.ts");
  const aliasDts = buildAliasDts(aliases);
  const content = `
// AUTO-GENERATED by vbox-type-gen
// Do not edit by hand. Regenerate with npx vbox-type-gen'

import type { AliasMap, ColorTokensInterface, FontSizeTokensInterface, FontWeightTokensInterface, FontFamilyTokensInterface, SpacingTokensInterface } from "@vbox/core";

declare module "@vbox/core" {
  ${aliasDts}
  ${buildThemeInterface(colors, "ColorTokensInterface")}
  ${buildThemeInterface(fontSizes, "FontSizeTokensInterface")}
  ${buildThemeInterface(fontWeights, "FontWeightTokensInterface")}
  ${buildThemeInterface(fontFamilies, "FontFamilyTokensInterface")}
  ${buildThemeInterface(spacings, "SpacingTokensInterface")}
}
  `;
  await fs.writeFile(outFile, content, "utf8");
};

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
