import { DefaultAliases } from '@veebox/core';

export const ObjectStyleKeys = new Set([
  'mq',
  'cq',
  'dark',
  'declarations',
  'pseudos',
  'hover',
  'focus',
  'focusVisible',
  'focusWithin',
  'active',
  '_disabled',
  'sm',
  'md',
  'lg',
  'xl',
  '_2xl',
]);

export const DefaultAliasKeys = new Set(Object.keys(DefaultAliases));

export const ExplicitStyleKeys = new Set([
  ...ObjectStyleKeys,
  ...DefaultAliasKeys,
]);

// Attributes that should never be interpreted as style props during native parsing.
// This protects semantic HTML/SVG behavior from collisions with CSS descriptor names
// present in broad property datasets (for example `src`, `alt`).
export const NonStyleAttributeKeys = new Set([
  'id',
  'class',
  'style',
  'title',
  'lang',
  'dir',
  'hidden',
  'tabindex',
  'contenteditable',
  'draggable',
  'spellcheck',
  'translate',
  'role',
  'slot',
  'is',
  'name',
  'value',
  'type',
  'placeholder',
  'disabled',
  'readonly',
  'required',
  'checked',
  'selected',
  'multiple',
  'min',
  'max',
  'step',
  'maxlength',
  'minlength',
  'pattern',
  'autocomplete',
  'autofocus',
  'for',
  'form',
  'src',
  'srcset',
  'sizes',
  'href',
  'target',
  'rel',
  'download',
  'ping',
  'referrerpolicy',
  'integrity',
  'crossorigin',
  'fetchpriority',
  'alt',
  'loading',
  'decoding',
  'usemap',
  'ismap',
  'poster',
  'preload',
  'controls',
  'muted',
  'loop',
  'playsinline',
  'autoplay',
  'kind',
  'srclang',
  'label',
  'open',
  'summary',
  'method',
  'action',
  'enctype',
  'novalidate',
  'accept',
  'accept-charset',
  'capture',
  'cols',
  'rows',
  'wrap',
  'colspan',
  'rowspan',
  'scope',
  'headers',
  'datetime',
  'cite',
  'reversed',
  'start',
  'sandbox',
  'allow',
  'allowfullscreen',
  'allowpaymentrequest',
  'frameborder',
  'marginwidth',
  'marginheight',
  'scrolling',
  'xmlns',
  'viewBox',
  'preserveAspectRatio',
  'd',
  'xlink:href',
]);
