import type { AliasMap } from "./types";

export const DefaultAliases: AliasMap = {
  w: "width",
  maxW: "maxWidth",
  minW: "minWidth",
  h: "height",
  maxH: "maxHeight",
  minH: "minHeight",
  fs: "fontSize",
  fw: "fontWeight",
  ff: "fontFamily",
  lh: "lineHeight",
  ls: "letterSpacing",
  m: "margin",
  mt: "marginTop",
  mb: "marginBottom",
  ml: "marginLeft",
  mr: "marginRight",
  mx: "marginInline",
  my: "marginBlock",
  p: "padding",
  pt: "paddingTop",
  pb: "paddingBottom",
  pl: "paddingLeft",
  pr: "paddingRight",
  px: "paddingInline",
  py: "paddingBlock",
  bg: "background",
  bgColor: "backgroundColor",
  bgSize: "backgroundSize",
  bgPosition: "backgroundPosition",
  bgImage: "backgroundImage",
  bgClip: "backgroundClip",
  bgRepeat: "backgroundRepeat",
  bgAttachment: "backgroundAttachment",
  bgOrigin: "backgroundOrigin",
  d: "display",
  radius: "borderRadius",
  shadow: "boxShadow",
};

export const TokensMap = {
  color: "colors",
  "font-size": "font-size",
  "font-weight": "font-weight",
  "font-family": "font-family",
  spacing: "spacing",
};

export const SpacingProperties = [
  "margin",
  "margin-top",
  "margin-block-start",
  "margin-bottom",
  "margin-block-end",
  "margin-block",
  "margin-right",
  "margin-inline-end",
  "margin-left",
  "margin-inline-start",
  "margin-inline",
  "padding",
  "padding-top",
  "padding-block-start",
  "padding-bottom",
  "padding-block-end",
  "padding-block",
  "padding-right",
  "padding-inline-end",
  "padding-left",
  "padding-inline-start",
  "padding-inline",
  "gap",
  "column-gap",
  "row-gap",
  "line-height",
  "letter-spacing",
] as const;
