import type { AliasMap } from "./types";

export const DefaultAliases: AliasMap = {
  w: "width",
  maxW: "maxWidth",
  minW: "minWidth",
  h: "height",
  maxH: "maxHeight",
  minH: "minHeight",
  fs: "fontSize",
  fw: "fontWeight",
  ff: "fontFamily",
  lh: "lineHeight",
  ls: "letterSpacing",
  m: "margin",
  mt: "marginTop",
  mb: "marginBottom",
  ml: "marginLeft",
  mr: "marginRight",
  mx: "marginInline",
  my: "marginBlock",
  p: "padding",
  pt: "paddingTop",
  pb: "paddingBottom",
  pl: "paddingLeft",
  pr: "paddingRight",
  px: "paddingInline",
  py: "paddingBlock",
  bg: "background",
  bgColor: "backgroundColor",
  bgSize: "backgroundSize",
  bgPosition: "backgroundPosition",
  bgImage: "backgroundImage",
  bgClip: "backgroundClip",
  bgRepeat: "backgroundRepeat",
  bgAttachment: "backgroundAttachment",
  bgOrigin: "backgroundOrigin",
  d: "display",
  radius: "borderRadius",
  shadow: "boxShadow",
};
